### ISSUE TITLE
这种检测方式会对http proxy over TLS误报吗？

### ISSUE THREAD

**Issue by box-hacker** [RPRX/Trojan-killer#8]
从理论分析的话，这种检测方式看起来会误报所有通过https proxy访问https的流量
但受限于环境，我没办法亲自验证我的想法，所以我提了一个issue，希望有条件的朋友可以试试看。
如果确实存在误报，是否说明TLS over TLS的方案仍然是安全的？

**Comment by RPRX** [comment]
> proxy

？GFW 想封的不就是 proxy？？
