### ISSUE TITLE
非常好项目，使我的代理更换

### ISSUE THREAD

**Issue by Menaed** [RPRX/Trojan-killer#9]
![40106829140233](https://github.com/XTLS/Trojan-killer/assets/92369968/ff0662f1-e500-49be-9b1d-96eb8f20cef6)

**Comment by chise0713** [comment]
issue 是拿来灌水用的？

**Comment by Menaed** [comment]
> issue 是拿來灌水用的

对不起！我还以为能删掉

**Comment by Fangliding** [comment]
这

**Comment by chise0713** [comment]
别有下一次就好。。。

**Comment by Menaed** [comment]
> 別有下一次就好。。。

好的！看文档把脑子看坏掉了
